### ISSUE TITLE
When user is in DND, Ludolph should postpone all alerts and reminders

### ISSUE THREAD

**Issue by secult** [erigones/Ludolph#68]
Even though the alert is customizable in zabbix, sometimes user uses the Do not disturb status in the xmpp client. In this case, ludolph should not notify user.
A nice to have feature would be that the missed alerts and reminders will be shown after the person changes state from DND.

**Comment by dn0** [comment]
The PR #71 adds some of the requested functionality. However, postponing of messages was not implemented because the current DB is not suitable for storing deferred messages. So messages to DND users are dropped. This, however, does not affect reminders as the remind command uses `attentions` instead of `messages`.
